### PR TITLE
Do not assume that _cmp functions return -1, 0, 1

### LINKED ISSUE #194: Test failure on 32-bit arches
I am attempting to build e-antic 1.0.1 for the Fedora Linux distribution.  The build succeeded on every 64-bit architecture, but tests failed on both 32-bit architectures (i686 and ARM).  In both cases, test-suite.log shows the following:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
t-cmp is a Catch v2.13.5 host application.
Run with -? for options

-------------------------------------------------------------------------------
Relational Operators with Integers - int
  Implications
-------------------------------------------------------------------------------
renfxx/t-cmp.cpp:48
...............................................................................

renfxx/t-cmp.cpp:76: FAILED:
  REQUIRE( not (a <= b) )
with expansion:
  false

-------------------------------------------------------------------------------
Relational Operators with Integers - long
  Implications
-------------------------------------------------------------------------------
renfxx/t-cmp.cpp:48
...............................................................................

renfxx/t-cmp.cpp:76: FAILED:
  REQUIRE( not (a <= b) )
with expansion:
  false

===============================================================================
test cases:     9 |     7 passed | 2 failed
assertions: 97081 | 97079 passed | 2 failed

FAIL renfxx/t-cmp (exit status: 2)
```

GDB shows that when this test fails, the value of b is -2147483648; i.e., the most negative integer, and the only integer besides zero that is the negation of itself.  Let me know if I can provide any other information.

### PR DESCRIPTION
**Pull request by saraedum**
Fixes #194, #211.

### CODE REVIEW

File: libeantic/src/renf_elem/get_d.c [hunk 1]
```diff
@@ -30,7 +30,7 @@ static int renf_elem_overflows_d(renf_elem_t a, renf_t nf)
         fmpz_set_d(dbl_max, DBL_MAX);
         int cmp = renf_elem_cmp_fmpz(a, dbl_max, nf);
         fmpz_clear(dbl_max);
-        return cmp == 1 ? 1 : 0;
+        return cmp >= 1 ? 1 : 0;
```
Comment (saraedum) [inline libeantic/src/renf_elem/get_d.c:33]:
```suggestion
        return cmp > 0 ? 1 : 0;
```

File: libeantic/src/renf_elem/fdiv.c [hunk 2]
```diff
@@ -69,7 +75,7 @@ void renf_elem_fdiv(fmpz_t a, renf_elem_t b, renf_elem_t c, renf_t nf)
             renf_elem_init(ac, nf);
             renf_elem_mul_fmpz(ac, c, a, nf);
 
-            if (renf_elem_cmp(ac, b, nf) == renf_elem_sgn(c, nf))
+            if (sgn(renf_elem_cmp(ac, b, nf)) == renf_elem_sgn(c, nf))
```
Comment (saraedum) [inline libeantic/src/renf_elem/fdiv.c:78]: According to our coverage tests, the left hand side is always 0. So this condition is never met during testing.

File: libeantic/srcxx/renf_elem_class.cpp [hunk 3]
```diff
@@ -239,8 +240,8 @@ bool relop_maybe_fmpz(const renf_elem_class& lhs, Integer rhs, const std::functi
     bool ret;
 
     maybe_fmpz(rhs,
-        [&](auto v) { ret = op(lhs.renf_elem_t(), v, lhs.parent().renf_t()) == cmp; },
-        [&](const fmpz_t v) { ret = renf_elem_cmp_fmpz(lhs.renf_elem_t(), v, lhs.parent().renf_t()) == cmp; });
+        [&](auto v) { ret = boost::math::sign(op(lhs.renf_elem_t(), v, lhs.parent().renf_t())) == cmp; },
+        [&](const fmpz_t v) { ret = boost::math::sign(renf_elem_cmp_fmpz(lhs.renf_elem_t(), v, lhs.parent().renf_t())) == cmp; });
```
Comment (saraedum) [inline libeantic/srcxx/renf_elem_class.cpp:244]: We should also make sure that this code path is tested.

Comment (saraedum) [reply libeantic/srcxx/renf_elem_class.cpp:244]: This code path would only be executed on Windows, so we cannot test it.
